name: CI
 
on:
  release:
    types:
      - published

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:
    inputs:
      ref:
        required: true
        default: 'main'
        type: string
        description: 'branch / tag or commit id to build'
      artifact-retention:
        required: true
        default: 7
        type: number
        description: 'artifact retention time in days'

jobs:
  build:
    name: Build generator
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.ref }}

    - name: "Checkout capicxx-core-tools"
      uses: actions/checkout@v6 
      with:
        repository: Vaillant-NEEXT/plsw-linux-tools-capicxx-core-tools
        path: capicxx-core-tools

    - name: Set up JDK 8
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Set up Maven
      run: |
        MAVEN_VERSION=3.9.6
        wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
        tar xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz
        echo "$PWD/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH

    - name: Build dependency
      run: mvn -f org.genivi.commonapi.core.releng/pom.xml -D target.id=org.genivi.commonapi.core.target clean verify
      working-directory: capicxx-core-tools
      
    - name: Build project
      run: mvn -D COREPATH=capicxx-core-tools -f org.genivi.commonapi.someip.releng/pom.xml -D target.id=org.genivi.commonapi.someip.target clean verify

    - name: Store artifact to action
      uses: actions/upload-artifact@v7
      with:
        name: commonapi-someip-generator
        path: org.genivi.commonapi.someip.cli.product/target/products/commonapi_someip_generator.zip
        if-no-files-found: error
        retention-days: ${{ inputs.artifact-retention || 7 }}

    - name: Store artifacts to release
      if: ${{ github.event_name == 'release' }}
      run: gh release upload ${{ github.ref_name }} org.genivi.commonapi.someip.cli.product/target/products/commonapi_someip_generator.zip